### ISSUE TITLE
Upon installing `ember-service-worker-emberfire-messaging` an error was shown

### ISSUE THREAD

**Issue by mikeelemuel** [Matt-Jensen/ember-service-worker-emberfire-messaging#9]
Hi, i installed the latest NPM however when I run `ember-service-worker-emberfire-messaging` an error was shown.

```
Installing packages for tooling via npm...module.js:491
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/Users/MacLem/Documents/site/MetroMart/metromart-team/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/MacLem/Documents/site/MetroMart/metromart-team/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

**Comment by Matt-Jensen** [comment]
Mike, I was just able to install this addon successfully on a new Ember app.

```
ember-cli: 3.0.0
node: 6.13.0
os: darwin x64
```

However, this error doesn't sound good: `Error: Cannot find module 'internal/fs'`.  [Does the fix discussed here help you at all](https://github.com/nodejs/node/issues/9377)?

**Comment by mikeelemuel** [comment]
Hmmm, that's strange. I'm using the latest version of `npm` I will try those approach now.

**Comment by Matt-Jensen** [comment]
I'm going to close this for now.  If you determine that your npm build is not at fault we can reopen.

**Comment by mikeelemuel** [comment]
Hi @Matt-Jensen are you active on ember slack community?
